/**
 * Builds the /try wallet bundle (src/web/try-wallet.ts + Pera / Lute + the x402 AVM client) into one
 * browser file and writes it as a string module: src/web/wallet-bundle.gen.ts (served by GET /try/wallet.js,
 * so it ships inside the serverless function with no static-file setup).
 *
 *   npm run build:wallet            write the module
 *   npm run build:wallet -- --check exit 1 if the committed module is not what the sources build to
 */
import { build } from "esbuild";
import { createHash } from "node:crypto";
import { readFileSync, writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";

const root = fileURLToPath(new URL("..", import.meta.url));
const OUT = `${root}src/web/wallet-bundle.gen.ts`;

export async function buildWalletJs(): Promise<string> {
  const r = await build({
    entryPoints: [`${root}src/web/try-wallet.ts`],
    bundle: true,
    write: false,
    format: "esm",
    platform: "browser",
    target: "es2020",
    minify: true,
    legalComments: "none",
    inject: [`${root}src/web/buffer-shim.ts`],
    define: { "process.env.NODE_ENV": '"production"', global: "globalThis" },
    logLevel: "silent",
  });
  return r.outputFiles[0].text;
}

export function moduleText(js: string): string {
  const sha = createHash("sha256").update(js).digest("hex").slice(0, 16);
  return `// GENERATED by scripts/build-wallet.ts from src/web/*.ts. Do not edit; run \`npm run build:wallet\`.\nexport const WALLET_JS_SHA = ${JSON.stringify(sha)};\nexport const WALLET_JS = ${JSON.stringify(js)};\n`;
}

if (import.meta.url === `file://${process.argv[1]}`) {
  const text = moduleText(await buildWalletJs());
  if (process.argv.includes("--check")) {
    const cur = readFileSync(OUT, "utf8");
    if (cur !== text) {
      console.error("src/web/wallet-bundle.gen.ts is stale: run npm run build:wallet");
      process.exit(1);
    }
    console.log("wallet bundle up to date");
  } else {
    writeFileSync(OUT, text);
    console.log(`wrote ${OUT} (${(text.length / 1024).toFixed(0)} KiB)`);
  }
}
